#
#  TODO: prepare connection to git for push upstream stuff !!!
#  TODO: use fresh and empty database volume from scratch !!
#  TODO: need to have local .git and git submodules for the correct treatment of git push upstream functionality
#
version: '3.1'

services:

  database:
    image: mysql
    container_name: my-mysql
    depends_on:
      copy-in-service:
        condition: service_completed_successfully
    networks:
      - dante-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10     
    secrets:
     - mysql_root_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password


  webserver:
    image: lap
    container_name: my-lap-container
    depends_on:
      database:
        condition: service_healthy
      copy-in-service:
        condition: service_completed_successfully
    volumes:
      - ../../volumes/full/content:/var/www/html
    ports:
      - "8080:80"
      - "4443:443"
    networks: 
      - dante-network
    environment:
      MODE: PHP


  copy-in-service:
    image: alpine
    volumes:
      - source_template:/from
      - /Users/cap/DOCKER/dante-wiki/volumes/full/content:/to
    command: >
      /bin/ash -c "cd /from && cp -a . /to ; sleep infinity"


  phpmyadmin:
    image: phpmyadmin:5.0
    ports: 
      - "9090:80"
    container_name: my-php-myadmin
    networks: 
      - dante-network
    environment:
      PMA_HOST: my-mysql
    depends_on:
      - database
      - webserver

volumes:
  source_template:
    name: volume-builder_volume-to-make





networks:
  dante-network:

secrets:
  mysql_root_password:
    file: ../../private/mysql-root-password.txt


