#
#
#
version: '3.1'

services:

  database:
    image: mysql
    container_name: my-mysql
    networks:
      - dante-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10     
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    command: 

#  database:
#    image: my-mysql
#    container_name: my-mysql
#    networks: 
#      - dante-network
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      timeout: 5s
#      retries: 10

  webserver:
    image: lap
    container_name: my-lap-container
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ../../volumes/full/content:/var/www/html
    ports:
      - "8080:80"
      - "4443:443"
    networks: 
      - dante-network
    environment:
      MODE: PHP

  phpmyadmin:
    image: phpmyadmin:5.0
    ports: 
      - "9090:80"
    container_name: my-php-myadmin
    networks: 
      - dante-network
    environment:
      PMA_HOST: my-mysql

networks:
  dante-network:

volumes:
  my-test-db-volume:
