#
#
#

services:

  database:
    image: dante-mysql
    container_name: my-dante-mysql
    networks:
      - dante-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 10     
      start_period: 40s
    secrets:
     - configuration
    volumes:
     - ../dante-mysql/mysql-init:/docker-entrypoint-initdb.d

  webserver:
    image: lap
    container_name: my-lap-container
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:80"
      - "4443:443"
    secrets:
      - configuration
    networks: 
      - dante-network
    command: "run-apache.sh init.sh"

  phpmyadmin:
    image: phpmyadmin:5.0
    ports: 
      - "9090:80"
    container_name: my-php-myadmin
    networks: 
      - dante-network
    environment:
      PMA_HOST: my-mysql

networks:
  dante-network:

secrets:
  configuration:
    file: ../../private/configuration.sh



