name: Count Lines of Code

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'

      - name: Install cloc
        run: sudo apt-get install cloc

      - name: Run cloc
        run: cloc .

      - name: Save results
        id: save-results
        run: |
          mkdir -p .github/results
          cloc .       > .github/results/cloc_results.txt
          cloc -json . > .github/results/cloc_results.json
          cloc -md .   > .github/results/cloc_results.md

      - name: Upload cloc results
        uses: actions/upload-artifact@v7
        with:
          name: cloc-results
          path: .github/results/
