name: Build and push multi-arch image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # find in github: Settings → Secrets and variables → Actions
          password: ${{ secrets.DOCKER_HUB_TOKEN }}    # find in github: Settings → Secrets and variables → Actions

      - name: Build and push (amd64 + arm64)
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: images/dante-wiki/src              # docker context
          push: true                                  # pushes it to dockerhub
          platforms: linux/amd64,linux/arm64
          tags: |
            clecap/dante-wiki:latest
            clecap/dante-wiki:dev