name: Docker Hub Vulnerability Scan

on:
#  schedule:
#    - cron: '0 0 * * *' # Runs daily at midnight
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch Docker Hub Scan Results
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_REPO: 'dante-wiki'
        DOCKER_HUB_TAG: 'latest'
      run: |
        python .github/scripts/fetch-scan-results.py

    - name: Commit JSON file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add scan_results.json
        git commit -m 'Update Docker Hub scan results'
        git push
