name: Docker Hub Vulnerability Scan

#on:
#  schedule:
#    - cron: '0 0 * * *' # Runs daily at midnight
#  push:
#    branches:
#      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4.8.0
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch Docker Hub Scan Results
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_REPO: 'tex'
        DOCKER_HUB_TAG: 'latest'
      run: |
        python .github/scripts/fetch-scan-results.py

    - name: Commit JSON file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add scan_results.json
        git commit -m 'Update Docker Hub scan results'
        git push
