on: [push]

jobs:
  scc_job:
    runs-on: ubuntu-latest
    name: A job to count the lines of code.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the lines of code.
        id: scc
        uses: Adapt-API/scc-docker-action@master
        with:
          args: ${{ env.workspace }} -i js,go,html,css
      - name: Echo scc output
        run: |
          echo
          echo -n "${{ steps.scc.outputs.scc }}"
          echo -n "${{ fromJson(steps.scc.outputs.scc)[0].Code }}"

