on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate SBOM
      run: |
        # Commands to generate your SBOM
        # Example: sbom-generator generate -o sbom.json
        echo '{"sbom": "example"}' > doc/sbom.json

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: doc/sbom.json
