name: Phan PHP Static code Analysis

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  phan:
    name: Run Phan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set up PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: '8.0' # Specify the PHP version you want to use
        tools: composer

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Install Phan
      run: composer require --dev phan/phan

    - name: Run Phan
      run: vendor/bin/phan --output mode=summary

    - name: Upload Phan results
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: phan-results
        path: phan-out/
