name: Phan PHP Static code Analysis

on:
  push:
    branches:
      - main

jobs:
  phan:
    name: Run Phan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Specify the PHP version you want to use
        tools: composer

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Install Phan
      run: composer require --dev phan/phan

    - name: Run Phan
      run: vendor/bin/phan --output mode=summary

    - name: Upload Phan results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: phan-results
        path: phan-out/
