name: Generate SBOM for Dockerfiles

on:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

concurrency:
  group: sbom-generation
  cancel-in-progress: false

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install syft (Anchore CLI)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin
          syft version

      - name: Generate SBOM for Docker image and repo
        run: |
          mkdir -p .github/results
          syft clecap/dante-wiki:latest -o json \
            > .github/results/sbom-dante-wiki-docker.json
          syft dir:. -o json \
            > .github/results/sbom-dante-wiki-docker-repo.json
          ls -alg .github/results

      - name: Upload SBOM files as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: .github/results/*.json