name: Generate SBOM for Dockerfiles

on:
  push:                                                  # generated at every push
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight

permissions:
  contents: read

concurrency:
  group: sbom-generation
  cancel-in-progress: false

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install syft (Anchore CLI)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin
          syft version

      - name: Generate SBOM for Docker image and repo
        run: |
          mkdir -p sbom
          syft clecap/dante-wiki:latest \
            -o json=sbom/sbom-dante-wiki-docker.json \
            -o table=sbom/sbom-dante-wiki-docker.txt \
            -o spdx-tag-value=sbom/sbom-dante-wiki-docker.spdx
          syft dir:. \
            -o json=sbom/sbom-dante-wiki-repo.json \
            -o table=sbom/sbom-dante-wiki-repo.txt \
            -o spdx-tag-value=sbom/sbom-dante-wiki-repo.spdx
          ls -alg sbom

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: sbom

  deploy-pages:
    needs: generate-sbom
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
